### PR TITLE
added Fextractor class for extracting features from a Fex instance

### PR DESCRIPTION
**Pull request by Nathaniel-Haines**
The Fextractor class works like this:

```
# cleaned data
df = read_facet('iMotions_Test.txt')
sessions = np.array([[x]*10 for x in range(1+int(len(df)/10))]).flatten()[:-1]
dat = Fex(df, sampling_freq=30, sessions=sessions)
dat = dat.interpolate(method='linear')

# Create instance of class
extractor = Fextractor()

# Extraction methods build a list of different features within extractor.extracted_features
extractor.mean(fex_object=dat)
extractor.max(fex_object=dat)
extractor.min(fex_object=dat)
#extractor.boft(fex_object=dat, min_freq=.01, max_freq=.20, bank=1) # boft not working yet
extractor.multi_wavelet(fex_object=dat)    
extractor.wavelet(fex_object=dat, freq=f, num_cyc=num_cyc)

# Merge and return all extracted features as a single wide or long DataFrame
newdat = extractor.merge(out_format='long')
```

Currently, it returns a pandas DataFrame. Also the boft extraction does not work (but I am not sure if that was already the case?). 

Anyway, this is a first attempt at a feature extraction class. Let me know what you think!

### CODE REVIEW

**Comment by jcheong0428** [comment]
@Nathaniel-Haines BofT was working but was broken when @ljchang was rewriting the wavelet function. Let me see if I can fix it.

**Comment by ljchang** [comment]
Looking forward to playing with this. Haven't looked at code yet, but a few thoughts based on your example.

1) Should we have an extractor method on Fex class that calls the new extractor class and extract methods ?  Seems handy from a streamlined workflow perspective.

2) How should we handle applying multiple feature extraction methods?  should this be input as a list of extraction methods or dictionary with variables to pass?  Should we require users to just chain methods? Or should we rely on the summary method?  

3) Also should we retain the original feature extraction methods on Fex?  or should they be completely moved into this new class?  My vote is to either retain them or add an extractor method.

**Comment by ljchang** [comment]
@Nathaniel-Haines looks like tests aren't passing now that @jcheong0428 has updated botf.  Want to add his change and see if that fixes it ?

**Comment by Nathaniel-Haines** [comment]
@ljchang I can add his change to see if it fixes things. Do I just need to pull from the master repo to update my local one?

**Comment by ljchang** [comment]
Yeah you should just be able to pull the new mater and merge those changes to your branch.  Then push the merged changes back to your PR.  should be pretty straightforward.

https://stackoverflow.com/questions/16955980/git-merge-master-into-feature-branch

**Comment by Nathaniel-Haines** [comment]
Thanks for the link! I was able to merge everything just fine. Hopefully the checks pass this time

**Pull request merged**
