### PR TITLE
plotting tutorial updated with additional info

### PR DESCRIPTION
**Pull request by jcheong0428**
also removed boolean from gaze plotting vector

### CODE REVIEW

**Comment by jcheong0428** [comment]
Python 2 test is failing because of changed super().__init__ on _ixs method. 
This notation works for python3 but not for 2. 
Not using this results in a infinite loop as duscussed below: 
https://stackoverflow.com/questions/576169/understanding-python-super-with-init-methods

**Comment by ljchang** [comment]
@jcheong0428: one idea I've been thinking about is the concept of "funneling", where we might replace the subclasses for each software into a single data class and then have an importer to convert the data from each software into a common data representation.  There are a lot of pros for this approach.  Not sure what exactly we will lose.  It would probably fix the super issue, though there must be a straightforward approach that is python 2 and 3 compliant

**Comment by ljchang** [comment]
Also, I assume you are cleaning up the plotting tutorial on this branch.  A lot of the tutorial code isn't working on my laptop.  We should also rename the blue.h5 file to something more descriptive.  I believe there should be separate models for each data type, but not sure if they are stored in the same hdf5 container

**Comment by jcheong0428** [comment]
Yup, @skbyrne just added descriptions about the models. We should rename the files too. 

The most recent tutorial `tutorials/plotting.py` isn't working? I just ran through it and was working for me. You might have to pull and reinstall as there have been many changes.  But yea it's buggy here and there and needs some cleaning up and more testing.

**Comment by ljchang** [comment]
got it working and cleaned it up.  The issue was with packaging and including the tests/data.

**Pull request merged**
